/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Cursor;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Isass
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            setIconImage(ImageIO.read(new File("src\\Recursos\\iconoEstacionamiento_1.png")));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        initComponents();
        configurarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        labelHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        bIngresar = new javax.swing.JButton();
        campoContraseña = new javax.swing.JPasswordField();
        radioSeguridad = new javax.swing.JRadioButton();
        radioAdmin = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        laMapa = new javax.swing.JLabel();
        labelPie = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Parking");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        labelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/headerLeon.png"))); // NOI18N
        labelHeader.setMinimumSize(new java.awt.Dimension(1366, 768));
        labelHeader.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Contraseña");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Usuario");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));
        jPanel1.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 200, 30));

        bIngresar.setBackground(new java.awt.Color(255, 204, 51));
        bIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(bIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 400, 40));
        jPanel1.add(campoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 30));

        grupo.add(radioSeguridad);
        radioSeguridad.setSelected(true);
        radioSeguridad.setText("Seguridad");
        radioSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSeguridadActionPerformed(evt);
            }
        });
        jPanel1.add(radioSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 90, -1));

        grupo.add(radioAdmin);
        radioAdmin.setText("Administrador");
        jPanel1.add(radioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio de Sesión");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tipo de usuario");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, -1));

        laMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/mapaitl.jpg"))); // NOI18N
        laMapa.setText("laMapa");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3259, Short.MAX_VALUE))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(laMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(labelPie, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(labelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addComponent(laMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPie, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(982, Short.MAX_VALUE))
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        // TODO add your handling code here:
        // en caso de que sea de caseta
        if (radioSeguridad.isSelected()) {
            if (campoUsuario.getText().equals("isai") && campoContraseña.getText().equals("123")) {

                this.dispose();
                Pantalla_Principal_Seguridad p = new Pantalla_Principal_Seguridad();
                p.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Usuario ó contraseña no válido", "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
            }

        } // en caso de que sea administrador
        else {
            
            if (campoUsuario.getText().equals("carreon") && campoContraseña.getText().equals("123")) {

                this.dispose();
                Pantalla_Principal_Administrador p = new Pantalla_Principal_Administrador();
                p.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Usuario ó contraseña no válido", "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_bIngresarActionPerformed

    private void radioSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSeguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSeguridadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    public javax.swing.JPasswordField campoContraseña;
    public javax.swing.JTextField campoUsuario;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel laMapa;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelPie;
    private javax.swing.JPanel panelPrincipal;
    public javax.swing.JRadioButton radioAdmin;
    public javax.swing.JRadioButton radioSeguridad;
    // End of variables declaration//GEN-END:variables

    private void configurarComponentes() {
        
        ImageIcon imagen1 = new ImageIcon("src\\Recursos\\headerLeon.png");
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(labelHeader.getWidth(), labelHeader.getHeight(), Image.SCALE_AREA_AVERAGING));
        labelHeader.setIcon(fondo1);
        this.repaint();
        
        ImageIcon imagen2 = new ImageIcon("src\\Recursos\\piePagina.png");
        Icon fondo2 = new ImageIcon(imagen2.getImage().getScaledInstance(labelPie.getWidth(), labelPie.getHeight(), Image.SCALE_SMOOTH));
        labelPie.setIcon(fondo2);
        this.repaint();
        
        ImageIcon imagen3 = new ImageIcon("src\\Recursos\\mapaitl.jpg");
        Icon fondo3 = new ImageIcon(imagen3.getImage().getScaledInstance(laMapa.getWidth(), laMapa.getHeight(), Image.SCALE_SMOOTH));
        laMapa.setIcon(fondo3);
        laMapa.setCursor(new Cursor(Cursor.HAND_CURSOR));
        laMapa.setBorder(BorderFactory.createTitledBorder(""));
//        laMapa.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
//        laMapa.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
        this.repaint();
        
        
        
    }
}
