/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;

/**
 *
 * @author Isass
 */
public class Pantalla_Añadir_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Añadir_Usuario
     */
    public Pantalla_Añadir_Usuario() {
        this.setVisible(true);
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComponents();
        configurarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        pestañaExterior = new javax.swing.JPanel();
        panelAlumno = new javax.swing.JPanel();
        botonGuardarUsuario = new javax.swing.JButton();
        campoNombre = new javax.swing.JTextField();
        campoColor = new javax.swing.JTextField();
        campoPlaca = new javax.swing.JTextField();
        campoModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoNoControl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoHoraEntrada = new javax.swing.JTextField();
        campoHoraSalida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoAño = new javax.swing.JTextField();
        campoFechaPago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabbedPane.setBackground(new java.awt.Color(0, 153, 255));
        TabbedPane.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TabbedPane.setOpaque(true);

        pestañaExterior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlumno.setBackground(new java.awt.Color(153, 204, 255));
        panelAlumno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonGuardarUsuario.setBackground(new java.awt.Color(255, 204, 51));
        botonGuardarUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonGuardarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        botonGuardarUsuario.setText("Registrar");
        panelAlumno.add(botonGuardarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        panelAlumno.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, -1));

        campoColor.setText(" ");
        panelAlumno.add(campoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, -1));

        campoPlaca.setText(" ");
        panelAlumno.add(campoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));

        campoModelo.setText(" ");
        panelAlumno.add(campoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, -1));

        jLabel6.setText("Nombre");
        panelAlumno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel8.setText("Color");
        panelAlumno.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 20));

        jLabel9.setText("Placa");
        panelAlumno.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel10.setText("Modelo");
        panelAlumno.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 20));

        jLabel11.setText("No. Control");
        panelAlumno.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        campoNoControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNoControlActionPerformed(evt);
            }
        });
        panelAlumno.add(campoNoControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel2.setText("Hora/Entrada");
        panelAlumno.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel3.setText("Hora/Salida");
        panelAlumno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        panelAlumno.add(campoHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 60, -1));
        panelAlumno.add(campoHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 60, -1));

        jLabel4.setText("Año");
        panelAlumno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel5.setText("Fecha/Pago");
        panelAlumno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));
        panelAlumno.add(campoAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 50, -1));
        panelAlumno.add(campoFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Personal");
        panelAlumno.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 60, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Transporte");
        panelAlumno.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, -1));
        panelAlumno.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 440, 10));
        panelAlumno.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 440, -1));

        pestañaExterior.add(panelAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 230));

        TabbedPane.addTab("Alumno", pestañaExterior);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registro de Usuario");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(TabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoNoControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNoControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNoControlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Añadir_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Añadir_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Añadir_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Añadir_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Añadir_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    public javax.swing.JButton botonGuardarUsuario;
    public javax.swing.JTextField campoAño;
    public javax.swing.JTextField campoColor;
    public javax.swing.JTextField campoFechaPago;
    public javax.swing.JTextField campoHoraEntrada;
    public javax.swing.JTextField campoHoraSalida;
    public javax.swing.JTextField campoModelo;
    public javax.swing.JTextField campoNoControl;
    public javax.swing.JTextField campoNombre;
    public javax.swing.JTextField campoPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelAlumno;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel pestañaExterior;
    // End of variables declaration//GEN-END:variables

    private void configurarComponentes() {
        
        this.botonGuardarUsuario.setEnabled(false);
        
    }
}
